### ISSUE TITLE
Center Important Content on Screen

### ISSUE THREAD

**Issue by ProelevateTeam** [ProelevateTeam/Weather-Web-App#2]
In the Weather React web app, the important content needs to be aligned to the center of the screen for better user experience. Please update the layout to ensure the key information is properly centered.

Currently we have : 
<img width="1440" alt="Screenshot 2024-09-30 at 4 18 00 PM" src="https://github.com/user-attachments/assets/b8954a71-b9fa-438f-8ecb-9617d6dc54a4">

We want : 
<img width="1440" alt="Screenshot 2024-09-30 at 4 20 00 PM" src="https://github.com/user-attachments/assets/2cc3e434-c0c0-4ce3-8ac4-e4c0ca5be3fe">

**Comment by NayakPenguin** [comment]
I am interested in this issue

**Comment by NayakPenguin** [comment]
@ProelevateTeam can you share env

**Comment by skartik-sk** [comment]
Is this issue is still open if yes I would like to solve this. @ProelevateTeam  plz assign me .

**Comment by ProelevateTeam** [comment]
Sorry the issue is resolved. But we will make new issues soon!
